apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-infra
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./deploy/K8s/infra/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-infra
  targetNamespace: default