apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: uploader-api
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./deploy/k8s/uploader/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: uploader-api
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: identity-api
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./deploy/k8s/identity/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: identity-api