apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: infra
  namespace: evolution
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/cloud-first-approach/Evolution.infra