# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# bases:
#   - ../../../infra/base
# patchesStrategicMerge:
# - ../../../infra/overlays/dev/configmap_patch.yaml

# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# resources:
# - infra-source.yaml
# - infra-kustomization.yaml
