apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flagger-system
commonLabels:
  app: flagger
commonAnnotations:
  app: flagger
resources:
  - tester/
  - namespace.yaml
  - account.yaml
  - crd.yaml
  - deployment.yaml



