### Create an App ###

POST https://localhost:5080/api/app
Content-Type: application/json

{
  "kind": "AdmissionReview",
  "apiVersion": "admission.k8s.io/v1",
  "request": {
    "uid": "9d92f45e-40d0-45da-89dd-b883b99268d6",
    "kind": {
      "group": "apps",
      "version": "v1",
      "kind": "Deployment"
    },
    "resource": {
      "group": "apps",
      "version": "v1",
      "resource": "deployments"
    },
    "name": "uploader-api",
    "namespace": "uploader",
    "operation": "CREATE",
    "userInfo": {
      "username": "docker-for-desktop",
      "groups": [
        "system:masters",
        "system:authenticated"
      ]
    },
    "object": {
      "kind": "Deployment",
      "apiVersion": "apps/v1",
      "metadata": {
        "name": "uploader-api",
        "namespace": "uploader",
        "uid": "8a3dea16-3c63-4428-9e2b-cb0fcbfa5bb3",
        "generation": 1,
        "creationTimestamp": "2023-08-02T22:47:29Z",
        "labels": {
          "app": "uploader-api",
          "metrics-scraper": "prom",
          "version": "v1"
        },
        "annotations": {
          "app": "uploader-api",
          "enable-canary-gates": "true"
        }
      },
      "spec": {
        "replicas": 1,
        "selector": {
          "matchLabels": {
            "app": "uploader-api",
            "metrics-scraper": "prom",
            "version": "v1"
          }
        },
        "template": {
          "metadata": {
            "creationTimestamp": null,
            "labels": {
              "app": "uploader-api",
              "metrics-scraper": "prom",
              "version": "v1"
            },
            "annotations": {
              "app": "uploader-api"
            }
          },
          "spec": {
            "volumes": [
              {
                "name": "imagestore",
                "persistentVolumeClaim": {
                  "claimName": "imagestoreclaim"
                }
              },
              {
                "name": "appsettings-volume",
                "configMap": {
                  "name": "appsettings",
                  "defaultMode": 420
                }
              }
            ],
            "containers": [
              {
                "name": "uploader-api",
                "image": "rohitrustagi007/evo_uploader:0.1.0",
                "ports": [
                  {
                    "name": "uploader-api",
                    "containerPort": 80,
                    "protocol": "TCP"
                  }
                ],
                "env": [
                  {
                    "name": "ASPNETCORE_ENVIRONMENT",
                    "value": "Production"
                  },
                  {
                    "name": "AWS_ACCESS_KEY",
                    "valueFrom": {
                      "secretKeyRef": {
                        "name": "access",
                        "key": "AWS_ACCESS_KEY"
                      }
                    }
                  },
                  {
                    "name": "AWS_SECRET_KEY",
                    "valueFrom": {
                      "secretKeyRef": {
                        "name": "secret",
                        "key": "AWS_SECRET_KEY"
                      }
                    }
                  }
                ],
                "resources": {
                  "limits": {
                    "cpu": "200m",
                    "memory": "256Mi"
                  },
                  "requests": {
                    "cpu": "100m",
                    "memory": "128Mi"
                  }
                },
                "volumeMounts": [
                  {
                    "name": "imagestore",
                    "mountPath": "/images"
                  },
                  {
                    "name": "appsettings-volume",
                    "mountPath": "/app/Settings"
                  }
                ],
                "livenessProbe": {
                  "httpGet": {
                    "path": "/healthz",
                    "port": 80,
                    "scheme": "HTTP"
                  },
                  "timeoutSeconds": 1,
                  "periodSeconds": 10,
                  "successThreshold": 1,
                  "failureThreshold": 3
                },
                "readinessProbe": {
                  "httpGet": {
                    "path": "/healthz",
                    "port": 80,
                    "scheme": "HTTP"
                  },
                  "timeoutSeconds": 1,
                  "periodSeconds": 10,
                  "successThreshold": 3,
                  "failureThreshold": 3
                },
                "startupProbe": {
                  "httpGet": {
                    "path": "/health",
                    "port": 80,
                    "scheme": "HTTP"
                  },
                  "timeoutSeconds": 1,
                  "periodSeconds": 10,
                  "successThreshold": 1,
                  "failureThreshold": 30
                },
                "terminationMessagePath": "/dev/termination-log",
                "terminationMessagePolicy": "File",
                "imagePullPolicy": "Always"
              }
            ],
            "restartPolicy": "Always",
            "terminationGracePeriodSeconds": 30,
            "dnsPolicy": "ClusterFirst",
            "securityContext": {
              
            },
            "schedulerName": "default-scheduler"
          }
        },
        "strategy": {
          "type": "RollingUpdate",
          "rollingUpdate": {
            "maxUnavailable": "25%",
            "maxSurge": "25%"
          }
        },
        "revisionHistoryLimit": 10,
        "progressDeadlineSeconds": 600
      },
      "status": {
        
      }
    },
    "oldObject": null,
    "dryRun": false,
    "options": {
      "kind": "CreateOptions",
      "apiVersion": "meta.k8s.io/v1",
      "fieldManager": "kubectl-client-side-apply",
      "fieldValidation": "Strict"
    }
  }
}